# This workflow will build a Npm Web project with Node.JS and create release
# author: https://github.com/itning

name: Auto Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Npm Install And Build
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm run electron:build
    - name: Archive Win Release
      uses: papeloto/action-zip@v1
      with:
        files: win-unpacked/
        dest: release-win.zip
    - name: Archive Mac Release
      uses: papeloto/action-zip@v1
      with:
        files: mac-unpacked/
        dest: release-mac.zip
    - name: Archive Linux Release
      uses: papeloto/action-zip@v1
      with:
        files: linux-unpacked/
        dest: release-linux.zip
